using Microsoft.Extensions.Configuration; using Microsoft.Extensions.Logging; using Npgsql; using UniversalSimulation.Application; using UniversalSimulation.Domain;
namespace UniversalSimulation.Infrastructure;
public sealed class PostgresSimulationStore(IConfiguration config, ILogger<PostgresSimulationStore> log) : ISimulationStore
{
    private readonly string cs = config.GetConnectionString("Postgres") ?? "Host=localhost;Database=universe;Username=universe;Password=universe";
    public async Task Initialize(CancellationToken ct) { await using var c = new NpgsqlConnection(cs); await c.OpenAsync(ct); var asm = typeof(PostgresSimulationStore).Assembly; await using var stream = asm.GetManifestResourceStream("UniversalSimulation.Infrastructure.Migrations.001_initial.sql")!; using var reader = new StreamReader(stream); await using var cmd = new NpgsqlCommand(await reader.ReadToEndAsync(ct), c); await cmd.ExecuteNonQueryAsync(ct); log.LogInformation("Database schema ready"); }
    public async Task<IReadOnlyList<UniverseState>> LoadAll(CancellationToken ct) { var x = new List<UniverseState>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(ct); await using var cmd = new NpgsqlCommand("select state_json from universes order by created_at", c); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(Snapshot.Deserialize(r.GetString(0))); return x; }
    public async Task Save(UniverseState u, IReadOnlyList<SimEvent> events, CancellationToken ct) { await using var c = new NpgsqlConnection(cs); await c.OpenAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); await using (var cmd = new NpgsqlCommand("insert into universes(id,name,state_json,created_at,updated_at) values($1,$2,$3::jsonb,$4,now()) on conflict(id) do update set name=$2,state_json=$3::jsonb,updated_at=now()", c, tx)) { cmd.Parameters.AddWithValue(u.Id); cmd.Parameters.AddWithValue(u.Name); cmd.Parameters.AddWithValue(Snapshot.Serialize(u)); cmd.Parameters.AddWithValue(u.CreatedAt); await cmd.ExecuteNonQueryAsync(ct); } foreach (var e in events) { await using var cmd = new NpgsqlCommand("insert into simulation_events values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) on conflict do nothing", c, tx); cmd.Parameters.AddWithValue(e.Id); cmd.Parameters.AddWithValue(e.UniverseId); cmd.Parameters.AddWithValue(e.Tick); cmd.Parameters.AddWithValue(e.Year); cmd.Parameters.AddWithValue(e.Type); cmd.Parameters.AddWithValue((int)e.Importance); cmd.Parameters.AddWithValue(e.Summary); cmd.Parameters.AddWithValue(e.Details); cmd.Parameters.AddWithValue((object?)e.ActorId ?? DBNull.Value); cmd.Parameters.AddWithValue((object?)e.LocationId ?? DBNull.Value); cmd.Parameters.AddWithValue((object?)e.CausedByEventId ?? DBNull.Value); cmd.Parameters.AddWithValue(e.RecordedAt); await cmd.ExecuteNonQueryAsync(ct); } await tx.CommitAsync(ct); }
    public async Task<IReadOnlyList<SimEvent>> Events(Guid id, int limit, EventImportance? min, CancellationToken ct) { var x = new List<SimEvent>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(ct); await using var cmd = new NpgsqlCommand("select id,universe_id,tick,year,type,importance,summary,details,actor_id,location_id,caused_by_event_id,recorded_at from simulation_events where universe_id=$1 and importance >= $2 order by tick desc,recorded_at desc limit $3", c); cmd.Parameters.AddWithValue(id); cmd.Parameters.AddWithValue((int)(min ?? 0)); cmd.Parameters.AddWithValue(Math.Clamp(limit,1,1000)); await using var r=await cmd.ExecuteReaderAsync(ct); while(await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetInt64(2),r.GetDouble(3),r.GetString(4),(EventImportance)r.GetInt32(5),r.GetString(6),r.GetString(7),r.IsDBNull(8)?null:r.GetGuid(8),r.IsDBNull(9)?null:r.GetGuid(9),r.IsDBNull(10)?null:r.GetGuid(10),r.GetFieldValue<DateTimeOffset>(11))); return x; }
    public async Task Delete(Guid id,CancellationToken ct) { await using var c=new NpgsqlConnection(cs); await c.OpenAsync(ct); await using var cmd=new NpgsqlCommand("delete from universes where id=$1",c); cmd.Parameters.AddWithValue(id); await cmd.ExecuteNonQueryAsync(ct); }
}
